version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    container_name: nginx
    depends_on:
      - php

  php:
    build: 
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: php